### ISSUE TITLE
Error on debug log

### ISSUE THREAD

**Issue by leo-combes** [calmh/node-snmp-native#59]
I found this error and it seems that I should publish it here:

`Woops! An error occurred while parsing an SNMP message. :(
To have this problem corrected, please report the information below verbatim
via email to snmp@nym.se or by creating a GitHub issue at
https://github.com/calmh/node-snmp-native/issues

Thanks!

AssertionError: 48 == 10
    at parse (/var/wwww/wampServer/node_modules/snmp-native/lib/snmp.js:223:12)
    at EventEmitter.msgReceived (/var/wwww/wampServer/node_modules/snmp-native/lib/snmp.js:405:15)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:549:8)

Message data:
    0a 

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: 48 == 10
    at parse (/var/wwww/wampServer/node_modules/snmp-native/lib/snmp.js:223:12)
    at EventEmitter.msgReceived (/var/wwww/wampServer/node_modules/snmp-native/lib/snmp.js:405:15)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:549:8)`

**Comment by calmh** [comment]
Something sent a 0x0a which is not a valid SNMP message. (I think I'll tone down the request to file an issue in the code. Thanks for following it nonetheless.)
