### ISSUE TITLE
Error occurred while parsing an SNMP message

### ISSUE THREAD

**Issue by Jaloko** [calmh/node-snmp-native#63]
Not sure what is causing this. I am doing a fair few SNMP requests per 5 sec and 60 sec. Let me know if you need more information. I should also add this happens infrequently but enough to be annoying.

Woops! An error occurred while parsing an SNMP message. :(
To have this problem corrected, please report the information below verbatim
via email to snmp@nym.se or by creating a GitHub issue at
https://github.com/calmh/node-snmp-native/issues

Thanks!

AssertionError: 48 == 66
    at parse (C:\Users\crb\Desktop\snmp\node_modules\snmp-native\lib\snmp.js:228:12)
    at EventEmitter.msgReceived (C:\Users\crb\Desktop\snmp\node_modules\snmp-native\lib\snmp.js:410:15)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:548:8)

Message data:
    42 00 00 00 05 33 f0 2c d1 1f c5 41 00 97 b0 32
    e2 1d 10 5b a4 c0 a8 40 80 ca 6f 01 00 00 00 0f
    00 57 00 49 00 4e 00 2d 00 43 00 4c 00 36 00 35
    00 33 00 32 00 47 00 45 00 44 00 42 00 48

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: 48 == 66
    at parse (C:\Users\crb\Desktop\snmp\node_modules\snmp-native\lib\snmp.js:228:12)
    at EventEmitter.msgReceived (C:\Users\crb\Desktop\snmp\node_modules\snmp-native\lib\snmp.js:410:15)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:548:8)

**Comment by Jaloko** [comment]
Another one:

Woops! An error occurred while parsing an SNMP message. :(
To have this problem corrected, please report the information below verbatim
via email to snmp@nym.se or by creating a GitHub issue at
https://github.com/calmh/node-snmp-native/issues

Thanks!

AssertionError: 48 == 83
    at parse (C:\Users\crb\Desktop\snmp\node_modules\snmp-native\lib\snmp.js:228:12)
    at EventEmitter.msgReceived (C:\Users\crb\Desktop\snmp\node_modules\snmp-native\lib\snmp.js:426:15)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:548:8)

Message data:
    53 70 6f 74 55 64 70 30 3b 42 e7 c7 16 0a 89 c7
    00 01 00 04 48 95 c2 03 54 94 14 6e f1 c2 ec f7
    60 92 ae a5 45 46 04 76 74 b5 ae 8b

events.js:160
      throw er; // Unhandled 'error' event
      ^
AssertionError: 48 == 83
    at parse (C:\Users\crb\Desktop\snmp\node_modules\snmp-native\lib\snmp.js:228:12)
    at EventEmitter.msgReceived (C:\Users\crb\Desktop\snmp\node_modules\snmp-native\lib\snmp.js:426:15)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:548:8)

**Comment by calmh** [comment]
Handle the error event and you can choose what to do with these errors, including ignoring them. They siginify an incoming packet that is not valid SNMP

**Comment by Jaloko** [comment]
I am handling the event now which works great for keeping the app running. But it still prints the entire error message each time which I don't want. Is there a way to stop this?

**Comment by calmh** [comment]
No, and that's a bug we should fix.
